import { createContext, useContext, useState } from "react";
import longArrow from "../assets/events/cardButtonIconLong.svg";
import arrow from "../assets/events/cardButtonIcon.svg";
const eventsData = [
    {
        id: 1,
        title: "ПОЙМАЙ МОМЕНТ",
        title1:"ПОЙМАЙ",
        title2:"МОМЕНТ",
        dates: "20.03 — 25.03",
        icon: arrow,
        iconMobile: longArrow, 
        iconClass:"shortCardIcon",
        iconClassMobile: "longCardIcon", 
        image:"/images/events/img1.png",
        inIcon1:"/images/events/inIcons/1-1.svg",
        inIcon2:"/images/events/inIcons/1-2.svg",
        inIcon3:"/images/events/inIcons/1-3.svg",
        inText1:"Живой формат",
        inText2:"Прогулка",
        inText3:"Атмосфера диалога",
        price:"600",
        paragraph1:"Откройте для себя искусство видеть — не глазами, а чувствами. Этот практикум посвящён уличной фотографии как способу наблюдать и фиксировать жизнь вокруг.",
        paragraph2:"Мы начнём с короткой теоретической части и примеров работ классиков стрит-фото, а затем — отправимся на прогулку по территории КРСТ и окрестностям.",
        paragraph3:"Это не просто фотоурок — это возможность посмотреть на привычный мир по‑новому и запечатлеть его уникальность через своё сердце и объектив. Присоединяйтесь к нам в этом увлекательном путешествии!"
    },
    {
        id: 2,
        title: "ЯРКИЕ ГОРИЗОНТЫ",
        title1:"ЯРКИЕ",
        title2:"ГОРИЗОНТЫ",
        dates: "10.04 — 15.04",
        icon: longArrow,
        iconMobile: arrow,
        iconClass:"longCardIcon",
        iconClassMobile: "shortCardIcon", 
        image:"/images/events/img2.png",
        inIcon1:"/images/events/inIcons/3-1.svg",
        inIcon2:"/images/events/inIcons/3-2.svg",
        inIcon3:"/images/events/inIcons/3-3.svg",
        inText1:"Интерактивный формат ",
        inText2:"Живые впечатления",
        inText3:"Свободное посещение",
        price:"800",
        paragraph1:"Погрузитесь в мир живых красок, музыки и творческой энергии! \"Яркие горизонты\" — это динамичный фестиваль, объединяющий уличных художников, перформанс-артистов и всех, кто ценит актуальное искусство.",
        paragraph2:"Это пятидневный творческий марафон в общественном пространстве, где искусство становится доступным каждому. Художники будут создавать муралы, музыканты — исполнять живые композиции, а перформансы удивят своей неординарностью.",
        paragraph3:"Особенность — интерактивность. Гости смогут участвовать в создании арт-объектов, посещать мастер-классы и наслаждаться вечерними концертами под открытым небом."
    },
    {
        id: 3,
        title: "ЗВУКИ ГОРОДА", 
        title1:"ЗВУКИ", 
        title2:"ГОРОДА", 
        dates: "14.04 — 30.04", 
        icon:arrow,
        iconMobile: arrow,
        iconClass:"shortCardIcon",
        iconClassMobile: "shortCardIcon", 
        image:"/images/events/img3.png", 
        inIcon1:"/images/events/inIcons/2-1.svg",
        inIcon2:"/images/events/inIcons/2-2.svg",
        inIcon3:"/images/events/inIcons/2-3.svg",
        inText1:"Аудиопрогулка",
        inText2:"Мастер-классы",
        inText3:"Интерактивная звуковая инсталляция",
        price:"900",
        paragraph1:"Город — это не только архитектура и люди, но и его уникальная звуковая палитра. Это мероприятие раскроет вам урбанистическую музыку: от ритмов метро до мелодий уличных музыкантов.",
        paragraph2:"Начнём с изучения основ звукозаписи в городской среде. Затем отправимся на прогулку, где каждый участник создаст свою звуковую карту района. Завершим встречу совместной импровизацией с использованием записанных звуков.",
        paragraph3:"Это не просто мероприятие — это новый способ услышать привычное пространство. Откройте для себя музыку, которая звучит вокруг нас каждый день."
    },
    {
        id: 4, 
        title: "КВЕСТ ЛАБИРИНТ", 
        title1:"КВЕСТ", 
        title2:"ЛАБИРИНТ", 
        dates: "10.04 — 20.04", 
        icon:arrow,
        iconMobile: arrow,
        iconClass:"shortCardIcon",
        iconClassMobile: "shortCardIcon", 
        image:"/images/events/img4.png", 
        inIcon1:"/images/events/inIcons/4-1.svg",
        inIcon2:"/images/events/inIcons/4-2.svg",
        inIcon3:"/images/events/inIcons/4-3.svg",
        inText1:"Командная игра",
        inText2:"Интерактивные головоломки",
        inText3:"Динамичные испытания",
        price:"1 500",
        paragraph1:"Затеряйтесь в мире головоломок и загадок! \"Квест Лабиринт\" — это уникальное приключение, где логика и интуиция помогут вам найти выход из самых неожиданных ситуаций.",
        paragraph2:"Участников ждёт серия интеллектуальных испытаний в специально оборудованных локациях. Каждый уровень — новый вызов, требующий смекалки и командной работы. Финалистов ожидает особый сюрприз!",
        paragraph3:"Это больше чем игра — это проверка вашей способности мыслить нестандартно. Соберите команду и испытайте себя!"
    },
    {
        id: 5, 
        title: "ТАЙНА ВРЕМЕНИ", 
        title1:"ТАЙНА", 
        title2:"ВРЕМЕНИ", 
        dates: "25.04 — 30.04", 
        icon:longArrow,
        iconMobile: arrow,
        iconClass:"longCardIcon",
        iconClassMobile: "shortCardIcon", 
        image:"/images/events/img5.png",
        inIcon1:"/images/events/inIcons/5-1.svg",
        inIcon2:"/images/events/inIcons/5-2.svg",
        inIcon3:"/images/events/inIcons/5-3.svg",
        inText1:"Интерактивная выставка",
        inText2:"Мастер-классы",
        inText3:"Исторические реконструкции", 
        price:"2 000",
        paragraph1:"Отправьтесь в путешествие сквозь эпохи! Это мероприятие раскроет вам секреты часовых механизмов и научит понимать язык времени.",
        paragraph2:"Вас ждёт знакомство с редкими хронометрами, создание собственных часовых механизмов и погружение в атмосферу разных исторических периодов через театрализованные представления.",
        paragraph3:"Это возможность прикоснуться к вечности. Откройте для себя магию времени!"
    },
    {
        id: 6, 
        title: "УЛИЧНЫЙ ТЕАТР", 
        title1:"УЛИЧНЫЙ", 
        title2:"ТЕАТР", 
        dates: "26.04", 
        icon:arrow,
        iconMobile: longArrow,
        iconClass:"shortCardIcon",
        iconClassMobile: "longCardIcon", 
        image:"/images/events/img6.png",
        inIcon1:"/images/events/inIcons/6-1.svg",
        inIcon2:"/images/events/inIcons/6-2.svg",
        inIcon3:"/images/events/inIcons/6-3.svg",
        inText1:"Живые постановки",
        inText2:"Интерактив со зрителями",
        inText3:"Карнавальное шествие", 
        price:"300",
        paragraph1:"Город становится сценой, а прохожие — зрителями! \"Уличный театр\" — это однодневный фестиваль перформансов, где профессиональные актёры и талантливые любители представят необычные спектакли под открытым небом.",
        paragraph2:"С 12:00 до 20:00 в центре общественного пространства будут идти спектакли в жанрах пантомимы, комедии дель арте и современной уличной драмы. Завершится фестиваль ярким карнавальным парадом с участием всех желающих!",
        paragraph3:"Это больше чем представление — это праздник, который стирает границы между искусством и жизнью."
    },
    {
        id: 7, 
        title: "МОДНЫЙ ВИНТАЖ", 
        title1:"МОДНЫЙ", 
        title2:"ВИНТАЖ", 
        dates: "15.05 — 31.05", 
        icon:longArrow,
        iconMobile: longArrow,
        iconClass:"longCardIcon",
        iconClassMobile: "longCardIcon", 
        image:"/images/events/img7.png",
        inIcon1:"/images/events/inIcons/7-1.svg",
        inIcon2:"/images/events/inIcons/7-2.svg",
        inIcon3:"/images/events/inIcons/7-3.svg",
        inText1:"Выставка-продажа",
        inText2:"Стилистические консультации",
        inText3:"Фотосессии", 
        price:"300",
        paragraph1:"Окунитесь в атмосферу прошлых десятилетий! \"Модный винтаж\" — это выставка-продажа уникальных вещей из разных эпох, где каждый найдёт свой особенный стиль.",
        paragraph2:"На протяжении двух недель в красивом лофт-пространстве будут представлены лучшие образцы винтажной моды. Вы сможете не только приобрести эксклюзивные вещи, но и узнать их историю, получить советы по созданию ретро-образов и сделать запоминающиеся фотографии в специально оформленных зонах.",
        paragraph3:""
    },
    {
        id: 8, 
        title: "ИГРОВАЯ АРЕНА", 
        title1:"ИГРОВАЯ", 
        title2:"АРЕНА", 
        dates: "01.05 — 15.05", 
        icon:longArrow,
        iconMobile: longArrow,
        iconClass:"longCardIcon",
        iconClassMobile: "longCardIcon",
        image:"/images/events/img8.png",
        inIcon1:"/images/events/inIcons/8-1.svg",
        inIcon2:"/images/events/inIcons/8-2.svg",
        inIcon3:"/images/events/inIcons/8-3.svg",
        inText1:"Турниры",
        inText2:"Свободная игра",
        inText3:"Тестирование новинок", 
        price:"500",
        paragraph1:"Настоящий рай для любителей игр! Две недели непрерывного игрового марафона, где каждый найдёт развлечение по душе — от классических настолок до новейших виртуальных миров.",
        paragraph2:"В просторном игровом центре вас ждут десятки игровых станций, где можно сразиться с друзьями или новыми знакомыми. Ежедневно проводятся турниры с ценными призами, работает зона для спокойных игр и площадка для тестирования самых свежих игровых новинок.",
        paragraph3:""
    },
    {
        id: 9, 
        title: "ТВОРЧЕСКАЯ ЛАВКА", 
        title1:"ТВОРЧЕСКАЯ", 
        title2:"ЛАВКА", 
        dates: "01.06 — 15.06", 
        icon:arrow,
        iconMobile: arrow,
        iconClass:"shortCardIcon",
        iconClassMobile: "shortCardIcon",  
        image:"/images/events/img9.png",
        inIcon1:"/images/events/inIcons/9-1.svg",
        inIcon2:"/images/events/inIcons/9-2.svg",
        inIcon3:"/images/events/inIcons/9-3.svg",
        inText1:"Мастер-классы",
        inText2:"Ярмарка ручной работы",
        inText3:"Творческий коворкинг", 
        price:"800",
        paragraph1:"Пространство, где оживают творческие идеи. Здесь собраны лучшие мастера, готовые поделиться своими умениями и вдохновить на создание собственных шедевров.",
        paragraph2:"Две недели творческого вдохновения! Каждый день проводятся разнообразные мастер-классы — от традиционных ремёсел до современных техник рукоделия. Вы сможете не только научиться новому, но и приобрести уникальные изделия местных мастеров или поработать над собственными проектами в уютной творческой атмосфере.",
        paragraph3:"Для тех, кто хочет поработать над своими проектами, работает творческий коворкинг с комфортными рабочими местами и всем необходимым оборудованием."
    },
    {
        id: 10,
        title: "ПЕСНЯ ЭПОХИ", 
        title1:"ПЕСНЯ", 
        title2:"ЭПОХИ", 
        dates: "12.06", 
        icon:longArrow,
        iconMobile: longArrow,
        iconClass:"longCardIcon",
        iconClassMobile: "longCardIcon",
        image:"/images/events/img10.png",
        inIcon1:"/images/events/inIcons/10-1.svg",
        inIcon2:"/images/events/inIcons/10-2.svg",
        inIcon3:"/images/events/inIcons/10-3.svg",
        inText1:"Концертная программа",
        inText2:"Просветительская лекция",
        inText3:"Открытая дискуссия", 
        price:"1 200",
        paragraph1:"Современная классическая музыка — это диалог времён, где традиции встречаются с новаторством. На этом мероприятии вы услышите, как композиторы XXI века создают звучание, отражающее дух нашей эпохи.",
        paragraph2:"Вечер начнётся с рассказа о главных направлениях в современной академической музыке. Затем прозвучат сочинения талантливых авторов в исполнении камерного ансамбля. В завершение гости смогут пообщаться с музыкантами и задать им вопросы.",
        paragraph3:"Это больше чем концерт — это погружение в мир, где каждая мелодия становится частью большого музыкального полотна. Приходите, чтобы услышать звуки, которые пишут историю сегодня."
    },
];

const DataContext = createContext();

export function DataProvider({ children }) {
    const [ items, setItems] = useState(eventsData);
    return (
        <DataContext.Provider value={{ items, setItems }}>
            {children}
        </DataContext.Provider>
    )
}

export function useData() {
    const context = useContext(DataContext);
    console.log(context)
    return context;
}